### ISSUE TITLE
校友请问你解决了MVSNet_pytorch中train loss不稳定的问题嘛？

### ISSUE THREAD

**Issue by whubaichuan** [Todd-Qi/TAPA-MVS#1]
校友请问你解决了MVSNet_pytorch中train loss不稳定的问题嘛？
https://github.com/xy-guo/MVSNet_pytorch/issues/11

**Comment by Todd-Qi** [comment]
好像是这样的，如果使用一张GPU，训练loss就不稳定。而作者训练时用的8块就是OK的

**Comment by whubaichuan** [comment]
方便加微信交流吗？我的是hbc862843076
